encoder: mamba
encoder_conf:
    pos_enc_layer_type: mamba
    mamba_type: bimamba_outer
    output_size: 512
    linear_units: 2048
    num_blocks: 12
    positional_dropout_rate: 0.1
    dropout_rate: 0.1
    Amatrix_type: factor_Gaussin
    input_layer: conv2d
    normalize_before: true
    macaron_style: true
    d_state: 16
    d_conv: 4
    expand: 2
    activation_type: swish
    use_cnn_module: true
    cnn_module_kernel: 31


decoder: transformer
decoder_conf:
    attention_heads: 8
    linear_units: 2048
    num_blocks: 6
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    self_attention_dropout_rate: 0.1
    src_attention_dropout_rate: 0.1

model_conf:
    ctc_weight: 0.3
    lsm_weight: 0.1
    length_normalized_loss: false

frontend_conf:
    n_fft: 512
    hop_length: 160

use_amp: true
batch_type: numel
batch_bins: 35000000
accum_grad: 4
max_epoch: 50
patience: none
init: none
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 10

optim: adam
optim_conf:
    lr: 0.0025
    weight_decay: 0.000001
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 40000

specaug: specaug
specaug_conf:
    apply_time_warp: true
    time_warp_window: 5
    time_warp_mode: bicubic
    apply_freq_mask: true
    freq_mask_width_range:
    - 0
    - 27
    num_freq_mask: 2
    apply_time_mask: true
    time_mask_width_ratio_range:
    - 0.
    - 0.05
    num_time_mask: 10
